export type Cocktail = {
  idDrink: string | string | null;
  strDrink: string;
  strDrinkAlternate: string;
  strTags: string;
  strVideo: string;
  strCategory: string;
  strIBA: string;
  strAlcoholic: string;
  strGlass: string;
  strInstructions: string;
  strInstructionsES: string;
  strInstructionsDE: string | null;
  strInstructionsFR: string | string | null;
  strInstructionsIT: string | string | null;
  strInstructionsZH_HANS: string | null;
  strInstructionsZH_HANT: string | string | null;
  strDrinkThumb: string | string | null;
  strIngredient1: string | string | null;
  strIngredient2: string | string | null;
  strIngredient3: string | string | null;
  strIngredient4: string | string | null;
  strIngredient5: string | null;
  strIngredient6: string | null;
  strIngredient7: string | null;
  strIngredient8: string | null;
  strIngredient9: string | null;
  strIngredient10: string | null;
  strIngredient11: string | null;
  strIngredient12: string | null;
  strIngredient13: string | null;
  strIngredient14: string | null;
  strIngredient15: string | null;
  strMeasure1: string | null;
  strMeasure2: string | null;
  strMeasure3: string | null;
  strMeasure4: string | null;
  strMeasure5: string | null;
  strMeasure6: string | null;
  strMeasure7: string | null;
  strMeasure8: string | null;
  strMeasure9: string | null;
  strMeasure10: string | null;
  strMeasure11: string | null;
  strMeasure12: string | null;
  strMeasure13: string | null;
  strMeasure14: string | null;
  strMeasure15: string | null;
  strImageSource: string | string | null;
  strImageAttribution: string | string | null;
  strCreativeCommonsConfirmed: string | string | null;
  dateModified: Date;
};
